# Generated by Django 4.2.1 on 2023-06-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAppT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='usos',
            field=models.SmallIntegerField(default=0, max_length=9000, verbose_name='Cantidad de Usos'),
        ),
    ]
